id: f1bbbb9b060f47199ac88e1081cf96ad
initial_creation_type: ocr
source_metadata:
  volumes:
    6ef69a12c304421f856caf49969ab63a:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ''
      total_pages: 1517
      volume_number: 77
